import Head from 'next/head'
import Title from '../components/Title'
import Dashboard from '../components/Dashboard'
import Footer from '../components/Footer'
import SliderAudio from '../components/SliderAudio'

export default function Home() {

  const user = {
    id: 1,
    email: "nicolasprieur22@gmail.com",
    name: "Nico",
    isAdmin: true
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <Title name={user.name} />

    {user.isAdmin ?(<>
      <p>Bonjour admin</p> <Dashboard /></>) 
      : (<p>vous êtes pas admin</p>)}

      <SliderAudio/>

      </main>
      

      <Footer/>
    </div>
  )
}